### ISSUE TITLE
Typing error using jotai 1.12.1 

### ISSUE THREAD

**Issue by devnomic** [jotai-labs/jotai-form#13]
I wanted to try this lib with latest jotai lib however it produce typing error. 

<img width="895" alt="Screen Shot 2023-01-15 at 20 33 11" src="https://user-images.githubusercontent.com/101681592/212543848-7ad09d42-fa93-43f9-af27-83f64078e869.png">

I literally followed the example in the readme.

````
// defining a validation schema for the atom
const emailSchema = Yup.string().email().required();

// creating the atom with an async validation function
const emailAtom = atomWithValidate('', {
  validate: async (v) => {
    await emailSchema.validate(v);
    return v;
  },
});


export default function SomeComponent() {
  const [email, setEmail] = useAtom(emailAtom); // error here
}
````

**Comment by dai-shi** [comment]
Sorry for the inconvenience.
v0.1.0 is already migrated Jotai v2 API (because we can use the prerelease in jotai v1).
In your case, please use v0.0.4 until jotai v2 is released.
```bash
npm install jotai-form@0.0.4
```

**Comment by devnomic** [comment]
I see thank you, however it produce another typing error when checking isValid like in the example.

<img width="944" alt="Screen Shot 2023-01-15 at 22 04 39" src="https://user-images.githubusercontent.com/101681592/212549071-181455c2-1066-4d96-a501-34ae1dbd03fd.png">

**Comment by dai-shi** [comment]
Can you create a minimal reproduction with https://codesandbox.io/s/react-typescript-react-ts ?

**Comment by devnomic** [comment]
Here it is:
https://codesandbox.io/s/ecstatic-paper-op43j5?file=/src/App.tsx

Sorry for long time.
I really like jotai, i think it's the best!

**Comment by dai-shi** [comment]
Thanks.
Because it's an async validation, it can be in progress. You need to check `isValidating` property.
https://codesandbox.io/s/charming-moon-1vycuk

**Comment by devnomic** [comment]
I see, thank you @dai-shi. It seems the readme basic example needs update then, since i just copy pasted the code from the readme.

**Comment by dai-shi** [comment]
Good point.

Would you be willing to open a PR?

Confirmed that examples/02 seems correct:
https://github.com/jotai-labs/jotai-form/blob/b52543d8ffedc17ebbb219d854a5aa1f247b8f95/examples/02_typescript/src/App.tsx#L29-L31
