### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by Sly777** [jotai-labs/jotai-form#16]
Hey @dai-shi and Jotai team, sorry to bother you, but do you still support this project?

**Comment by dai-shi** [comment]
@barelyhuman is a core maintainer. I think this project is fairly alive.

**Comment by barelyhuman** [comment]
It is, there’s quite a few additions that I wish to add which are right now just in my personal projects. 

Based on the DX i like, it’ll be a part of this project. For now, it’s the smallest working atom with Jotai

**Comment by Sly777** [comment]
Thanks a lot for updates! We started to use this on one of big projects so if you need any help, I can also join on maintaining this :)
