### ISSUE TITLE
Multi Level / Mixed Schema API 

### ISSUE THREAD

**Issue by barelyhuman** [jotai-labs/jotai-form#2]
A more general use case when working with forms involves a bigger schema from yup / joi. 
These are done in the following ways 
```js
const CreateAccountSchema = Yup.object().shape({
  firstName: Yup.string()
    .min(2, 'Too Short!')
    .max(70, 'Too Long!')
    .required('Required'),
  lastName: Yup.string()
    .min(2, 'Too Short!')
    .max(70, 'Too Long!')
    .required('Required'),
  email: Yup.string().email('Invalid email').required('Required'),
  password: Yup.string()
    .min(8, 'Password too short')
    .max(70, 'Password too long')
    .matches(
      /^(?![\s])(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^\w])([^\s]){8,}$/,
    )
    .required('Required'),
});
```
Which we can't work with when working with atoms but I'd like to add a way into the API to support defining multi atom schema.
Here's what I think would work with the Jotai style of doing things 

```js
const schemas = {
  firstName: Yup.string()
    .min(2, "Too Short!")
    .max(70, "Too Long!")
    .required("Required"),
  lastName: Yup.string()
    .min(2, "Too Short!")
    .max(70, "Too Long!")
    .required("Required"),
};

const firstName = atomWithValidate(0, {
  validate: (v) => {
    const result = schemas.firstName.validate(v);
    if (result.error) {
      throw result.error;
    }
    return result.value;
  },
});

const lastName = atomWithValidate(0, {
  validate: (v) => {
    const result = schemas.lastName.validate(v);
    if (result.error) {
      throw result.error;
    }
    return result.value;
  },
});

const formSchemaAtom = mergeAtoms({
  firstName,
  lastName,
});

const inComponent = () => {
  const { formState } = useAtom(formSchemaAtom);
  return (
    <>
      {formState.firstName.value}
      {formState.firstName.error}
      {formState.firstName.isDirty}
      {formState.firstName.error}
    </>
  );
};
```

Might have to add `mergeAtoms` logic to the original library, or add it as `mergeSchema` and limit it to this library.

This is open for discussion

**Comment by dai-shi** [comment]
This is basically a mismatch with atomic model, but I understand where it comes from.

I would expect something like this:
```js
const firstNameAtom = atomWithValidate('', {
  validate: (v) => pickYupSchema('firstName', CreateAccountSchema).validate(v),
});
```

It can support nesting:
```js
  pickYupSchema('person.fistName', CreateAccountSchema);
  // or
  pickYupSchema(['person', 'fistName'], CreateAccountSchema);
```

**Comment by dai-shi** [comment]
Alternatively, we could make a big atom and pick/select/focus out of it.

```js
const formAtom = atomWithValidate({}, {
  validate: (v) => CreateAccountSchema.validate(v),
});

const firstNameAtom = pickAtomWithValidate('firstName', formAtom);
```
Not sure if it's possible to implement.

**Comment by barelyhuman** [comment]
> This is basically a mismatch with atomic model, but I understand where it comes from.
> 
> I would expect something like this:
> 
> ```js
> const firstNameAtom = atomWithValidate('', {
>   validate: (v) => pickYupSchema('firstName', CreateAccountSchema).validate(v),
> });
> ```
> 
> It can support nesting:
> 
> ```js
>   pickYupSchema('person.fistName', CreateAccountSchema);
>   // or
>   pickYupSchema(['person', 'fistName'], CreateAccountSchema);
> ```

This makes more sense to me, though the `pick` part could be just a function param in `validate` to make it even cleaner ?

**Comment by dai-shi** [comment]
I prefer `validate` property to be validation-library agnostic.
So, it can work with any library:
```js
const fooAtom = atomWithValidate({}, {
  validate: validateWithYup(yupSchema),
});

const barAtom = atomWithValidate({}, {
  validate: validateWithJoi(joiSchema),
});
```
Or, anything. I learned this idea from react-hook-form.

Notice, `validateWithYup` and `validateWithJoi` can be implemented pretty easily.

---
In this case, the following would be more natural:
```js
const firstNameAtom = atomWithValidate('', {
  validate: (v) => validateWithYup(CreateAccountSchema, ['firstName']),
});
```

**Comment by barelyhuman** [comment]
> In this case, the following would be more natural:
> 
> ```js
> const firstNameAtom = atomWithValidate('', {
>   validate: (v) => validateWithYup(CreateAccountSchema, ['firstName']),
> });
> ```

okay, the point of the `picker` would've been to help pick the schema property but this works too. 
since `validate` is just a function, anything should be fine

**Comment by barelyhuman** [comment]
handled in #14
