### ISSUE TITLE
[CTA] Looking for Maintainers

### ISSUE THREAD

**Issue by barelyhuman** [jotai-labs/jotai-form#33]
Been a while since I've been able to commit time to `jotai-form` or OSS contributions in general. 

As much as I'd like to keep contributing, the maintainer role isn't something I'm able to live up to right now and would like to pass it on to someone who'd be happy to maintain the library. 

If you are interested in doing so, please reply here and we'll help you with the next steps

**Comment by L-Qun** [comment]
I’m very interested in becoming the maintainer of this project.

**Comment by dai-shi** [comment]
Sounds great!

I gave @L-Qun the maintainer role in this repository. You can do anything including changing some tooling like eslint. If you have questions feel free to drop messages.

For some design decisions, you may ask @barelyhuman and hope they can respond when they have time.

**Comment by L-Qun** [comment]
@dai-shi Could you also add me as a maintainer of jotai-scheduler https://github.com/jotaijs/jotai-scheduler

**Comment by dai-shi** [comment]
Done. (I didn't know how the transferred repo has permissions. Usually write permission would be enough.)

**Comment by barelyhuman** [comment]
That was quick! 
@L-Qun thanks a ton! and do let me know if there's anything you wish to discuss :)
